--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Steellgold/DamageModifier
build-by-default: true
branches:
- main
projects:
  DamageModifier:
    path: ""
    icon: DamageModifier.png
...
