# Please do not move these numbers
version: "1.0"

items:
  # ItemID-ItemMeta
  264-0:
    # Define the world where the changes will be applied
    # If you define others, then remove the all and separate with a comma your worlds, if you want it to be everywhere, then do not change the "all".
    worlds: [world]
    damage: 10
    # If you want the player's pushback to be modified but randomly then set on a scale of 100 a number
    # The number zero will be that the functionality is disabled and the number of KB defined is each time
    # If the chance is set to 30, then the player will have a 30 percent chance of repelling the entity or player tapped with the knockback set
    knockback: 10
    knockback-chance: 0